### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by mblund** [knoldus/play-reactive-slick#1] opened 2015-03-24 13:57 UTC
I tried to load test your test application with 
```
ab -n 1000 -c 5 http://localhost:9000/employees                    ~
This is ApacheBench, Version 2.3 <$Revision: 1554214 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
...
Completed 800 requests
Completed 900 requests
apr_socket_recv: Connection refused (61)
Total of 992 requests completed
```

but I got an out of memory exception and a crash after ~1000 request

```
Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Uncaught error from thread [play-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
Uncaught error from thread [play-akka.actor.default-dispatcher-6] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
Uncaught error from thread [play-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
play]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:713)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runSynchronousDatabaseAction(DatabaseComponent.scala:208)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:185)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInternal(DatabaseComponent.scala:63)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.run(DatabaseComponent.scala:60)
	at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:36)
[ERROR] [03/24/2015 14:47:57.322] [play-akka.actor.default-dispatcher-4] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:713)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runSynchronousDatabaseAction(DatabaseComponent.scala:208)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:185)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInternal(DatabaseComponent.scala:63)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.run(DatabaseComponent.scala:60)
	at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:36)
	at models.DAO$.count(DAO.scala:36)
	at models.DAO$.list(DAO.scala:84)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:44)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:43)
	at play.api.mvc.Action$.invokeBlock(Action.scala:556)
	at play.api.mvc.Action$.invokeBlock(Action.scala:555)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at models.DAO$.count(DAO.scala:36)
	at models.DAO$.list(DAO.scala:84)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:44)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:43)
	at play.api.mvc.Action$.invokeBlock(Action.scala:556)
	at play.api.mvc.Action$.invokeBlock(Action.scala:555)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)

	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[ERROR] [03/24/2015 14:47:57.322] [play-akka.actor.default-dispatcher-6] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-6] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:713)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runSynchronousDatabaseAction(DatabaseComponent.scala:208)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:185)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInternal(DatabaseComponent.scala:63)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.run(DatabaseComponent.scala:60)
	at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:36)
	at models.DAO$.count(DAO.scala:36)
	at models.DAO$.list(DAO.scala:84)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:44)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:43)
	at play.api.mvc.Action$.invokeBlock(Action.scala:556)
	at play.api.mvc.Action$.invokeBlock(Action.scala:555)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:713)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)[ERROR] [03/24/2015 14:47:57.322] [play-akka.actor.default-dispatcher-3] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:713)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runSynchronousDatabaseAction(DatabaseComponent.scala:208)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseCompone
nt.scala:185)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInternal(DatabaseComponent.scala:63)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:36)
	at slick.backend.DatabaseComponent$DatabaseDef$class.run(DatabaseComponent.scala:60)
	at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:36)
	at models.DAO$.count(DAO.scala:36)
	at models.DAO$.list(DAO.scala:84)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:44)
	at controllers.Application$$anonfun$list$1.apply(Application.scala:43)
	at play.api.mvc.Action$.invokeBlock(Action.scala:556)
	at play.api.mvc.Action$.invokeBlock(Action.scala:555)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

Have you seen this problem and do you have a clue why its happening?

**Comment by mblund** [comment] 2015-03-24 17:37
I looks like the database connection is closed properly
https://github.com/knoldus/play-reactive-slick/blob/master/app/models/DAO.scala#L87

But there is maybe need for some kind of push back or throttling.

**Comment by mblund** [comment] 2015-03-24 18:35
I managed to get a stacktrace with kill -3

Except for the usual akka, play and netty threads,  I got around 1900 hits of "AsyncExecutor.default-1", almost all of them in state_  WAITING (parking)

```
"AsyncExecutor.default-1" daemon prio=5 tid=0x00007f9adb6c9800 nid=0x64803 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"AsyncExecutor.default-1" daemon prio=5 tid=0x00007f9addc9c000 nid=0x64603 waiting on condition [0x0000000144e32000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007eeb10c60> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:374)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by szeiger** [comment] 2015-03-25 11:19
The app creates and closes a new Database instance for every database action. This means a new thread pool and connection pool are created every time. Unless there's some place where you create a db but do not close it afterwards, it still should not OOM. OTOH, if you overload the app and the db can't keep up, this could happen, because all the Database objects are separate and there is no back-pressure handling that prevents you from creating new ones while the existing ones can't keep up.

The right way to use Slick is to create a Database instance (ideally using Slick's new config syntax, otherwise make sure you configure the AsyncExecutor correctly) when the app starts, and close it when the app shuts down. This limits the number of concurrent requests and gives you a queue for back-pressure. When the queue is full and the database can't keep up, DBIO actions will fail immediately.

**Comment by mblund** [comment] 2015-03-25 11:57
Thanks for your comment szeiger. I will dive into the documentation and give it a try.

**Comment by mblund** [comment] 2015-03-25 13:01
I changed to 
```
val db: Database = Database.forDataSource(DB.getDataSource(),
    executor = AsyncExecutor("test1", numThreads=10, queueSize=1000)
  )
```
and then I removed all db.close call from each dao method
```
  /**
   * Count total employees in database
   */
  override def count: Future[Int] =
    db.run(employees.length.result)

  /**
   * Find employee by id
   */
  override def findById(id: Long): Future[Employee] =  {
    db.run(filterQuery(id).result.head)
  }
  ...
```

And now it is working fine. I'm able to load test it with lots of request with no problem. My kill -3 now give a reasonable number of threads.

**Comment by szeiger** [comment] 2015-03-25 13:13
:thumbsup:

**Closed** 2015-03-25 13:13 UTC

**Comment by mblund** [comment] 2015-03-25 14:15
My fix: https://github.com/mblund/play-reactive-slick/commit/19a4340dfa78ba39d8382fe421f020ce97fc6ef8

**Comment by apismensky** [comment] 2015-07-14 22:05
I just had the same problem with the application - I ran a JMeter load test script against it and saw the number of threads increasing and then the app crashed with OutOfMemory error. If had seen this post before - It would save a lot of time for me. @mblund - I will try to apply your fix, thanks a lot. 
Also I've created an API endpoints using Slick and plain JDBC and I want to compare their performance side-by-side. If you are interested - here is my fork - https://github.com/apismensky/play-reactive-slick. The load test is in the root (loadtest.jmx)
@szeiger - I think it would be nice to reflect this in the official documentation (HOWTO for Play applications, I mean - 
val db: Database = Database.forDataSource(DB.getDataSource(),
    executor = AsyncExecutor("test1", numThreads=10, queueSize=1000)
  )).

**Comment by szeiger** [comment] 2015-07-15 08:21
@apismensky The new Play-Slick plugin for Play 2.4 & Slick 3.0 handles all of this. It's generally recommended to use Play 2.4 or higher for Slick 3.x because it supports Slick's data source configuration system and works with Reactive Streams.

**Comment by apismensky** [comment] 2015-07-15 16:35
@szeiger - thanks for your response. I will try it with Play 2.4.* today. 
With the fix that @mblund found for this issue (and Play 2.3.9)  I re-ran load tests for both Slick and JDBC versions of API. With relatively low load (500 concurrent requests) JDBC has a little bit better performance (~25%).
When I increased a load to 2000 requests the Slick API had a much higher error rate ~40% compared to plain JBDC ~2%. All errors in Slick were caused by “Timed out waiting for a free available connection.” issue. 
I hope that migration to Play 2.4 will improve the situation.

**Comment by mblund** [comment] 2015-07-15 16:44
@apismensky maybe you could try to increase the queuesize?

**Comment by apismensky** [comment] 2015-07-15 17:18
@mblund - with 
 val db: Database = Database.forDataSource(DB.getDataSource(),
    executor = AsyncExecutor("test1", numThreads=100, queueSize=10000))
It reduced the error rate to ~ 3.0% but I'm still seeing a lot of  "Timed out waiting for a free available connection".
